spring.application.name=main
# Local PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/mainuser
spring.datasource.username= ${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port
server.port=8080